services:
  - type: web
    name: mdgroup-ctms-frontend
    runtime: static
    rootDir: mdgroup-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://mdgroup-ctms-api.up.railway.app/api
